### ISSUE TITLE
Bug - random_enemy() crashes when in wetlands

### ISSUE THREAD

**Issue by HexTree** [cowboy8625/WordRPG#6]
############################################
#                                          #
#                                          #
#          Location: Field                 #
#                                          #
#                                          #
############################################
Which way do you want to travel?

(1): North
(2): South
(3): East
(4): West
(5): Inspect Area
(6): Inventory
(7): Look For Resources
Input a Number:>  3
Traceback (most recent call last):
  File "Main.py", line 654, in <module>
    main()
  File "Main.py", line 134, in main
    char_creation()
  File "Main.py", line 258, in char_creation
    main_game_loop()
  File "Main.py", line 605, in main_game_loop
    main_game_loop()
  File "Main.py", line 635, in main_game_loop
    inspect_area(map_info[0][2])
  File "Main.py", line 571, in inspect_area
    main_game_loop()
  File "Main.py", line 635, in main_game_loop
    inspect_area(map_info[0][2])
  File "Main.py", line 571, in inspect_area
    main_game_loop()
  File "Main.py", line 605, in main_game_loop
    main_game_loop()
  File "Main.py", line 635, in main_game_loop
    inspect_area(map_info[0][2])
  File "Main.py", line 571, in inspect_area
    main_game_loop()
  File "Main.py", line 610, in main_game_loop
    encounter()
  File "Main.py", line 286, in encounter
    main_game_loop()
  File "Main.py", line 619, in main_game_loop
    encounter()
  File "Main.py", line 280, in encounter
    random_enemy()
  File "Main.py", line 267, in random_enemy
    mob = Mobs.hostail_mobs[random_mob]
KeyError: 'None'

**Comment by HexTree** [comment]
A fix went in, but the core bug is still present with a different field.

############################################
#                                          #
#                                          #
#          Location: Field                 #
#                                          #
#                                          #
############################################
Which way do you want to travel?

(1): North
(2): South
(3): East
(4): West
(5): Inspect Area
(6): Inventory
(7): Look For Resources
Input a Number:>  2
Traceback (most recent call last):
  File "Main.py", line 657, in <module>
    main()
  File "Main.py", line 134, in main
    char_creation()
  File "Main.py", line 258, in char_creation
    main_game_loop()
  File "Main.py", line 608, in main_game_loop
    main_game_loop()
  File "Main.py", line 652, in main_game_loop
    main_game_loop()
  File "Main.py", line 608, in main_game_loop
    main_game_loop()
  File "Main.py", line 608, in main_game_loop
    main_game_loop()
  File "Main.py", line 608, in main_game_loop
    main_game_loop()
  [Previous line repeated 1 more times]
  File "Main.py", line 613, in main_game_loop
    encounter()
  File "Main.py", line 289, in encounter
    main_game_loop()
  File "Main.py", line 613, in main_game_loop
    encounter()
  File "Main.py", line 283, in encounter
    random_enemy()
  File "Main.py", line 270, in random_enemy
    mob = Mobs.hostail_mobs[random_mob]
KeyError: 'Wolf'

**Comment by HexTree** [comment]
The problem is that the biomes and mobs are using dictionaries with hardcoded strings in a very unsafe way. This needs to be completely overhauled.

**Comment by HexTree** [comment]
Fixed in eb89c4a3ad5d76de1c58271d44406cf6db62541a
